set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(TOOLCHAIN_PREFIX arm-none-eabi)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
find_program(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
find_program(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
find_program(ARM_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy)
find_program(ARM_SIZE ${TOOLCHAIN_PREFIX}-size)

set(CMAKE_C_STANDARD 11)
set(CMAKE_C_EXTENSIONS ON)