#!/bin/bash

# ============================================================================
# STACK COLLECTOR
# Analyzes stack usage from .su files generated by compiler
# ============================================================================

collect_stack_data() {
    # Requires: STACK_SIZE_DEC
    
    # Stack usage from .su files (exclude STM32Cube HAL)
    export STACK_USED=$(find . -name "*.su" ! -path "*/STM32CubeG4/*" -exec awk '{sum+=$2} END {print sum}' {} + 2>/dev/null)
    export STACK_USED=${STACK_USED:-0}
    
    # Calculate free stack
    export STACK_FREE=$((STACK_SIZE_DEC - STACK_USED))
    export STACK_PERCENT=$((STACK_USED * 100 / STACK_SIZE_DEC))
    
    # Find top 3 stack consumers
    export LARGEST_FUNCS=$(find . -name "*.su" ! -path "*/STM32CubeG4/*" -exec cat {} \; 2>/dev/null | sort -k2 -n -r | head -3)
    
    return 0
}